on:
  push:
    branches:
      - main
      - dev
    paths:
      - "adapters/CitizensAdapter/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "adapters/CitizensAdapter/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test Adapter
        run: ./gradlew test --scan
        working-directory: ./adapters/CitizensAdapter
      - name: Build Adapter
        run: ./gradlew buildRelease --scan
        working-directory: ./adapters/CitizensAdapter
      - name: Upload Adapter
        uses: actions/upload-artifact@v2
        with:
          name: CitizensAdapter.jar
          path: adapters/CitizensAdapter/build/libs/CitizensAdapter.jar
